/**
 * Paper-to-Human — export helpers (Copy / Download .txt).
 *
 * The download header block is mandated by SPEC Section 4.5 and required by
 * the study's fact-checking protocol (Methodology Section G). Do not omit or
 * reorder the header lines.
 */

export interface ExportVersion {
  summary: string;
  concepts: string;
  analogy: string;
}

export interface ExportMetric {
  /** null when the text was too degenerate to score — see /api/translate. */
  fh: number | null;
}

/**
 * Reconstruct a version as plain text with its section headers — used both
 * for the clipboard "Copy" action and as the `[content]` of a downloaded file.
 */
export function versionPlainText(v: ExportVersion): string {
  return [
    `SUMMARY\n${v.summary}`,
    `KEY CONCEPTS\n${v.concepts}`,
    `REAL-WORLD ANALOGY\n${v.analogy}`,
  ]
    .join("\n\n")
    .trim();
}

/**
 * Build the full .txt file contents, including the exact SPEC 4.5 header block:
 *
 *   Generated by Paper-to-Human
 *   Date: [date]
 *   Source: [filename or URL]
 *   Fernández-Huerta: [score] | Nivel: [nombre]
 *   ---
 *   [content]
 */
export function buildExportFile(opts: {
  version: ExportVersion;
  metric: ExportMetric;
  nivel: string;
  source: string;
  date?: string;
}): string {
  const date = opts.date ?? new Date().toISOString().slice(0, 10);
  const header = [
    "Generated by Paper-to-Human",
    `Date: ${date}`,
    `Source: ${opts.source}`,
    `Fernández-Huerta: ${opts.metric.fh ?? "n/d"} | Nivel: ${opts.nivel}`,
    "---",
  ].join("\n");
  return `${header}\n${versionPlainText(opts.version)}\n`;
}
